services:
  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4442-4444:4442-4444"
    networks: [dockernet]

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2g
    depends_on: [selenium-hub]
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks: [dockernet]

  firefox:
    image: selenium/node-firefox:latest
    shm_size: 2g
    depends_on: [selenium-hub]
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks: [dockernet]

networks:
  dockerNet2026: